
export enum SoundType {
    UNUSEDMISCELLANEOUS = 0,
    SPELLS              = 1,
    UI                  = 2,
    FOOTSTEPS1          = 3,
    WEAPONSIMPACT       = 4,
    WEAPONSMISS         = 6,
    GREETINGS           = 7,
    CASTING             = 8,
    PICKUPPUTDOWN       = 9,
    NPCCOMBAT           = 10,
    ERRORS              = 12,
    BIRDS               = 13,
    OBJECTS             = 14,
    DEATH               = 16,
    NPCGREETINGS        = 17,
    TESTTEMPORARY       = 18,
    ARMORFOLEY          = 19,
    FOOTSTEPS2          = 20,
    WATERCHARACTER      = 21,
    WATERLIQUID         = 22,
    TRADESKILLS         = 23,
    DOODADS             = 25,
    SPELLFIZZLE         = 26,
    NPCLOOPS            = 27,
    ZONEMUSIC           = 28,
    EMOTES              = 29,
    NARRATIONMUSIC      = 30,
    NARRATION           = 31,
    ZONEAMBIENCE        = 50,
}