#pragma once

#include "Tracy.hpp"

#include <map>

#define WORLD_UPDATE_COLOR       0x6ADEFC
#define MAP_UPDATE_COLOR         0xFCD96A
#define DATABASE_UPDATE_COLOR    0x80E66B
#define HOOKS_WORLD_COLOR        0x80E66B
#define HOOKS_AUCTION_COLOR      0xFF5733
#define HOOKS_WEATHER_COLOR      0x33A1FF
#define HOOKS_VEHICLE_COLOR      0xFF33A1
#define HOOKS_ACHIEVEMENT_COLOR  0x57FF33
#define HOOKS_PLAYER_COLOR       0xA1FF33
#define HOOKS_ACCOUNT_COLOR      0x3357FF
#define HOOKS_GUILD_COLOR        0xFF33FF
#define HOOKS_GROUP_COLOR        0xFFD700
#define HOOKS_UNIT_COLOR         0x33FF57
#define HOOKS_SPELL_COLOR        0x5733FF
#define HOOKS_CREATURE_COLOR     0xFF6B33
#define HOOKS_GAMEOBJECT_COLOR   0x33FFAA
#define HOOKS_MAP_COLOR          0xFFAA33
#define HOOKS_BATTLEGROUND_COLOR 0xAA33FF
#define HOOKS_INSTANCE_COLOR     0x33FF33
#define HOOKS_ITEM_COLOR         0xA133FF
#define HOOKS_QUEST_COLOR        0x33FFAA
#define HOOKS_AREATRIGGER_COLOR  0xFF3333
#define HOOKS_SMARTACTION_COLOR  0x33A1A1
#define HOOKS_CONDITION_COLOR    0xA1FF57
#define HOOKS_CUSTOMPACKET_COLOR 0x5733A1
#define HOOKS_WORLDPACKET_COLOR  0xFF7F50
#define HOOKS_GAMEEVENT_COLOR    0x33FF66

extern std::map<std::pair<uint32,uint32>, uint32> relocations;
