import { GameObjectTemplate } from "./GameObjectTemplate";
import { GameObjectAreaDamage } from "./Types/GameObjectAreaDamage";
import { GameObjectAuraGenerator } from "./Types/GameObjectAuraGenerator";
import { GameObjectBarberChair } from "./Types/GameObjectBarberChair";
import { GameObjectButton } from "./Types/GameObjectButton";
import { GameObjectCamera } from "./Types/GameObjectCamera";
import { GameObjectCapturePoint } from "./Types/GameObjectCapturePoint";
import { GameObjectChair } from "./Types/GameObjectChair";
import { GameObjectChest } from "./Types/GameObjectChest";
import { GameObjectDestructibleBuilding } from "./Types/GameObjectDestructibleBuilding";
import { GameObjectDoor } from "./Types/GameObjectDoor";
import { GameObjectDungeonDifficulty } from "./Types/GameObjectDungeonDifficulty";
import { GameObjectFishingHole } from "./Types/GameObjectFishingHole";
import { GameObjectFlagDrop } from "./Types/GameObjectFlagDrop";
import { GameObjectFlagStand } from "./Types/GameObjectFlagStand";
import { GameObjectGeneric } from "./Types/GameObjectGeneric";
import { GameObjectGoober } from "./Types/GameObjectGoober";
import { GameObjectGuardPost } from "./Types/GameObjectGuardPost";
import { GameObjectGuildBank } from "./Types/GameObjectGuildBank";
import { GameObjectMailbox } from "./Types/GameObjectMailbox";
import { GameObjectMeetingStone } from "./Types/GameObjectMeetingStone";
import { GameObjectMinigame } from "./Types/GameObjectMinigame";
import { GameObjectMoTransport } from "./Types/GameObjectMoTransport";
import { GameObjectQuestGiver } from "./Types/GameObjectQuestGiver";
import { GameObjectSpellCaster } from "./Types/GameObjectSpellCaster";
import { GameObjectSpellFocus } from "./Types/GameObjectSpellFocus";
import { GameObjectSummoningRitual } from "./Types/GameObjectSummoningRitual";
import { GameObjectText } from "./Types/GameObjectText";
import { GameObjectTransport } from "./Types/GameObjectTransport";
import { GameObjectTrap } from "./Types/GameObjectTrap";
import { GameObjectTrapdoor } from "./Types/GameObjectTrapdoor";

export class GameObjectBase extends GameObjectTemplate<GameObjectBase> {
    setTrapdoor() { return new GameObjectTrapdoor(this.row); }
    setTrap() { return new GameObjectTrap(this.row); }
    setTransport() { return new GameObjectTransport(this.row); }
    setText() { return new GameObjectText(this.row); }
    setSummoningRitual() { return new GameObjectSummoningRitual(this.row); }
    setSpellFocus() { return new GameObjectSpellFocus(this.row); }
    setSpellCaster() { return new GameObjectSpellCaster(this.row); }
    setQuestGiver() { return new GameObjectQuestGiver(this.row); }
    setMoTransport() { return new GameObjectMoTransport(this.row); }
    setMinigame() { return new GameObjectMinigame(this.row); }
    setMeetingStone() { return new GameObjectMeetingStone(this.row); }
    setMailbox() { return new GameObjectMailbox(this.row); }
    setGuildbank() { return new GameObjectGuildBank(this.row); }
    setGuardPost() { return new GameObjectGuardPost(this.row); }
    setGoober() { return new GameObjectGoober(this.row); }
    setGeneric() { return new GameObjectGeneric(this.row); }
    setFlagStand() { return new GameObjectFlagStand(this.row); }
    setFlagDrop() { return new GameObjectFlagDrop(this.row); }
    setFishingHole() { return new GameObjectFishingHole(this.row); }
    setDungeonDifficulty() { return new GameObjectDungeonDifficulty(this.row); }
    setDoor() { return new GameObjectDoor(this.row); }
    setDestructibleBuilding() { return new GameObjectDestructibleBuilding(this.row); }
    setChest() { return new GameObjectChest(this.row); }
    setChair() { return new GameObjectChair(this.row); }
    setCapturePoint() { return new GameObjectCapturePoint(this.row); }
    setCamera() { return new GameObjectCamera(this.row); }
    setButton() { return new GameObjectButton(this.row); }
    setBarberChair() { return new GameObjectBarberChair(this.row); }
    setAuraGenerator() { return new GameObjectAuraGenerator(this.row); }
    setAreaDamage() { return new GameObjectAreaDamage(this.row); }
}