/*
 * This file is part of tswow (https://github.com/tswow)
 *
 * Copyright (C) 2020 tswow <https://github.com/tswow/>
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
import { LUAXML } from "../../luaxml/LUAXML";
import { LuaStringProperty } from "./Components/LuaProperty";

const GSLua = LUAXML.file('Interface/GlueXML/GlueStrings.lua');

export class GlueStrings {
    private prop(index: number) {
        return new LuaStringProperty(this,GSLua.emptyReplace(index));
    }

    get ABILITY_INFO_BLOODELF1() {return this.prop(3); }
    get ABILITY_INFO_BLOODELF2() {return this.prop(4); }
    get ABILITY_INFO_BLOODELF3() {return this.prop(5); }
    get ABILITY_INFO_BLOODELF4() {return this.prop(6); }
    get ABILITY_INFO_DRAENEI1() {return this.prop(7); }
    get ABILITY_INFO_DRAENEI2() {return this.prop(8); }
    get ABILITY_INFO_DRAENEI3() {return this.prop(9); }
    get ABILITY_INFO_DRAENEI4() {return this.prop(10); }
    get ABILITY_INFO_DWARF1() {return this.prop(11); }
    get ABILITY_INFO_DWARF2() {return this.prop(12); }
    get ABILITY_INFO_DWARF3() {return this.prop(13); }
    get ABILITY_INFO_DWARF4() {return this.prop(14); }
    get ABILITY_INFO_DWARF5() {return this.prop(15); }
    get ABILITY_INFO_GNOME1() {return this.prop(16); }
    get ABILITY_INFO_GNOME2() {return this.prop(17); }
    get ABILITY_INFO_GNOME3() {return this.prop(18); }
    get ABILITY_INFO_GNOME4() {return this.prop(19); }
    get ABILITY_INFO_HUMAN1() {return this.prop(20); }
    get ABILITY_INFO_HUMAN2() {return this.prop(21); }
    get ABILITY_INFO_HUMAN3() {return this.prop(22); }
    get ABILITY_INFO_HUMAN4() {return this.prop(23); }
    get ABILITY_INFO_HUMAN5() {return this.prop(24); }
    get ABILITY_INFO_NIGHTELF1() {return this.prop(25); }
    get ABILITY_INFO_NIGHTELF2() {return this.prop(26); }
    get ABILITY_INFO_NIGHTELF3() {return this.prop(27); }
    get ABILITY_INFO_NIGHTELF4() {return this.prop(28); }
    get ABILITY_INFO_ORC1() {return this.prop(29); }
    get ABILITY_INFO_ORC2() {return this.prop(30); }
    get ABILITY_INFO_ORC3() {return this.prop(31); }
    get ABILITY_INFO_ORC4() {return this.prop(32); }
    get ABILITY_INFO_SCOURGE1() {return this.prop(33); }
    get ABILITY_INFO_SCOURGE2() {return this.prop(34); }
    get ABILITY_INFO_SCOURGE3() {return this.prop(35); }
    get ABILITY_INFO_SCOURGE4() {return this.prop(36); }
    get ABILITY_INFO_TAUREN1() {return this.prop(37); }
    get ABILITY_INFO_TAUREN2() {return this.prop(38); }
    get ABILITY_INFO_TAUREN3() {return this.prop(39); }
    get ABILITY_INFO_TAUREN4() {return this.prop(40); }
    get ABILITY_INFO_TROLL1() {return this.prop(41); }
    get ABILITY_INFO_TROLL2() {return this.prop(42); }
    get ABILITY_INFO_TROLL3() {return this.prop(43); }
    get ABILITY_INFO_TROLL4() {return this.prop(44); }
    get ABILITY_INFO_TROLL5() {return this.prop(45); }
    get ACCEPT() {return this.prop(46); }
    get ACCOUNT_CREATE_FAILED() {return this.prop(47); }
    get ACCOUNT_CREATE_IN_PROGRESS() {return this.prop(48); }
    get ACCOUNT_CREATE_SUCCESS() {return this.prop(49); }
    get ACCOUNT_CREATE_URL() {return this.prop(50); }
    get ACCOUNT_MESSAGE_BODY_NO_READ_URL() {return this.prop(51); }
    get ACCOUNT_MESSAGE_BODY_URL() {return this.prop(52); }
    get ACCOUNT_MESSAGE_BUTTON_READ() {return this.prop(53); }
    get ACCOUNT_MESSAGE_HEADERS_URL() {return this.prop(54); }
    get ACCOUNT_MESSAGE_READ_URL() {return this.prop(55); }
    get ACCOUNT_NAME() {return this.prop(56); }
    get ACCOUNT_OPTIONS() {return this.prop(57); }
    get ADDONS() {return this.prop(58); }
    get ADDONS_OUT_OF_DATE() {return this.prop(59); }
    get ADDON_BANNED() {return this.prop(60); }
    get ADDON_BANNED_TOOLTIP() {return this.prop(61); }
    get ADDON_CORRUPT() {return this.prop(62); }
    get ADDON_DEPENDENCIES() {return this.prop(63); }
    get ADDON_DEP_BANNED() {return this.prop(64); }
    get ADDON_DEP_CORRUPT() {return this.prop(65); }
    get ADDON_DEP_DISABLED() {return this.prop(66); }
    get ADDON_DEP_INCOMPATIBLE() {return this.prop(67); }
    get ADDON_DEP_INSECURE() {return this.prop(68); }
    get ADDON_DEP_INTERFACE_VERSION() {return this.prop(69); }
    get ADDON_DEP_MISSING() {return this.prop(70); }
    get ADDON_DISABLED() {return this.prop(71); }
    get ADDON_FORCE_LOAD() {return this.prop(72); }
    get ADDON_INCOMPATIBLE() {return this.prop(73); }
    get ADDON_INSECURE() {return this.prop(74); }
    get ADDON_INTERFACE_VERSION() {return this.prop(75); }
    get ADDON_LIST() {return this.prop(76); }
    get ADDON_SECURE() {return this.prop(77); }
    get ADDON_UPDATE_AVAILABLE() {return this.prop(78); }
    get AGI() {return this.prop(79); }
    get ALL() {return this.prop(80); }
    get ALLIANCE() {return this.prop(81); }
    get ALL_SETTINGS() {return this.prop(82); }
    get ALPHA_BUILD() {return this.prop(83); }
    get AMBIENCE_VOLUME() {return this.prop(84); }
    get AMMO() {return this.prop(85); }
    get ANISOTROPIC() {return this.prop(86); }
    get APPLY() {return this.prop(87); }
    get ARM() {return this.prop(88); }
    get ARMOR() {return this.prop(89); }
    get ASSERTIONS_ENABLED_BUILD() {return this.prop(90); }
    get AUTHENTICATOR() {return this.prop(91); }
    get AUTH_ALREADY_LOGGING_IN() {return this.prop(92); }
    get AUTH_ALREADY_ONLINE() {return this.prop(93); }
    get AUTH_BAD_SERVER_PROOF() {return this.prop(94); }
    get AUTH_BANNED() {return this.prop(95); }
    get AUTH_BANNED_URL() {return this.prop(96); }
    get AUTH_BILLING_ERROR() {return this.prop(97); }
    get AUTH_BILLING_EXPIRED() {return this.prop(98); }
    get AUTH_DB_BUSY() {return this.prop(99); }
    get AUTH_DB_BUSY_URL() {return this.prop(100); }
    get AUTH_FAILED() {return this.prop(101); }
    get AUTH_INCORRECT_PASSWORD() {return this.prop(102); }
    get AUTH_LOCALE_MISMATCH() {return this.prop(103); }
    get AUTH_LOCKED_ENFORCED() {return this.prop(104); }
    get AUTH_LOGIN_SERVER_NOT_FOUND() {return this.prop(105); }
    get AUTH_NO_TIME() {return this.prop(106); }
    get AUTH_NO_TIME_URL() {return this.prop(107); }
    get AUTH_OK() {return this.prop(108); }
    get AUTH_PARENTAL_CONTROL() {return this.prop(109); }
    get AUTH_PARENTAL_CONTROL_URL() {return this.prop(110); }
    get AUTH_REJECT() {return this.prop(111); }
    get AUTH_SERVER_SHUTTING_DOWN() {return this.prop(112); }
    get AUTH_SESSION_EXPIRED() {return this.prop(113); }
    get AUTH_SUSPENDED() {return this.prop(114); }
    get AUTH_SUSPENDED_URL() {return this.prop(115); }
    get AUTH_SYSTEM_ERROR() {return this.prop(116); }
    get AUTH_UNAVAILABLE() {return this.prop(117); }
    get AUTH_UNKNOWN_ACCOUNT() {return this.prop(118); }
    get AUTH_VERSION_MISMATCH() {return this.prop(119); }
    get AUTH_WAIT_QUEUE() {return this.prop(120); }
    get AVAILABLE_CLASSES() {return this.prop(121); }
    get BACK() {return this.prop(122); }
    get BAG_SLOTS() {return this.prop(123); }
    get BATTLEFIELD_ALERT() {return this.prop(124); }
    get BETA_BUILD() {return this.prop(125); }
    get BF_DEATHS() {return this.prop(126); }
    get BF_HONOR_KILLS() {return this.prop(127); }
    get BF_HONOR_POINTS() {return this.prop(128); }
    get BF_KILLBLOWS() {return this.prop(129); }
    get BF_RANK() {return this.prop(130); }
    get BILLING_FIXED_IGR() {return this.prop(131); }
    get BILLING_FIXED_LASTDAY() {return this.prop(132); }
    get BILLING_FREE_TIME_EXPIRE() {return this.prop(133); }
    get BILLING_GAMEROOM_EXPIRE() {return this.prop(134); }
    get BILLING_HAS_FALLBACK_PAYMENT() {return this.prop(135); }
    get BILLING_IGR_USAGE() {return this.prop(136); }
    get BILLING_IGR_USAGE_TIME_LEFT_30_MINS() {return this.prop(137); }
    get BILLING_TEXT1() {return this.prop(138); }
    get BILLING_TEXT2() {return this.prop(139); }
    get BILLING_TEXT3() {return this.prop(140); }
    get BILLING_TEXT4() {return this.prop(141); }
    get BILLING_TIME_LEFT_30_MINS() {return this.prop(142); }
    get BILLING_TIME_LEFT_DAYS() {return this.prop(143); }
    get BILLING_TIME_LEFT_LAST_DAY() {return this.prop(144); }
    get BLIZZ_DISCLAIMER() {return this.prop(145); }
    get BLOCK() {return this.prop(146); }
    get BLOODELF_DISABLED() {return this.prop(147); }
    get BONUS_DAMAGE() {return this.prop(148); }
    get BONUS_HEALING() {return this.prop(149); }
    get BURNING_CRUSADE() {return this.prop(150); }
    get CALCULATING() {return this.prop(151); }
    get CANCEL() {return this.prop(152); }
    get CANCEL_RESET() {return this.prop(153); }
    get CANCEL_RESET_SETTINGS() {return this.prop(154); }
    get CATEGORY_DESCRIPTION() {return this.prop(155); }
    get CATEGORY_DESCRIPTION_TEXT() {return this.prop(156); }
    get CHANGE() {return this.prop(157); }
    get CHANGED_OPTIONS_WARNING_TITLE() {return this.prop(158); }
    get CHANGE_REALM() {return this.prop(159); }
    get CHARACTER_CREATE_ACCEPT() {return this.prop(160); }
    get CHARACTER_NAME() {return this.prop(161); }
    get CHARACTER_SELECT_INFO() {return this.prop(162); }
    get CHARACTER_SELECT_INFO_GHOST() {return this.prop(163); }
    get CHAR_CREATE_ACCOUNT_LIMIT() {return this.prop(164); }
    get CHAR_CREATE_CHARACTER_IN_GUILD() {return this.prop(165); }
    get CHAR_CREATE_DISABLED() {return this.prop(166); }
    get CHAR_CREATE_ERROR() {return this.prop(167); }
    get CHAR_CREATE_EXPANSION() {return this.prop(168); }
    get CHAR_CREATE_EXPANSION_CLASS() {return this.prop(169); }
    get CHAR_CREATE_FAILED() {return this.prop(170); }
    get CHAR_CREATE_INVALID_NAME() {return this.prop(171); }
    get CHAR_CREATE_IN_PROGRESS() {return this.prop(172); }
    get CHAR_CREATE_LEVEL_REQUIREMENT() {return this.prop(173); }
    get CHAR_CREATE_NAME_IN_USE() {return this.prop(174); }
    get CHAR_CREATE_ONLY_EXISTING() {return this.prop(175); }
    get CHAR_CREATE_PVP_TEAMS_VIOLATION() {return this.prop(176); }
    get CHAR_CREATE_SERVER_LIMIT() {return this.prop(177); }
    get CHAR_CREATE_SERVER_QUEUE() {return this.prop(178); }
    get CHAR_CREATE_SUCCESS() {return this.prop(179); }
    get CHAR_CREATE_UNIQUE_CLASS_LIMIT() {return this.prop(180); }
    get CHAR_CREATE_UNKNOWN() {return this.prop(181); }
    get CHAR_CUSTOMIZATION0_DESC() {return this.prop(182); }
    get CHAR_CUSTOMIZATION1_DESC() {return this.prop(183); }
    get CHAR_CUSTOMIZATION2_DESC() {return this.prop(184); }
    get CHAR_CUSTOMIZATION3_DESC() {return this.prop(185); }
    get CHAR_CUSTOMIZATION4_DESC() {return this.prop(186); }
    get CHAR_CUSTOMIZATION5_DESC() {return this.prop(187); }
    get CHAR_CUSTOMIZATION6_DESC() {return this.prop(188); }
    get CHAR_CUSTOMIZE_FAILED() {return this.prop(189); }
    get CHAR_CUSTOMIZE_IN_PROGRESS() {return this.prop(190); }
    get CHAR_DECLINE_FAILED() {return this.prop(191); }
    get CHAR_DECLINE_IN_PROGRESS() {return this.prop(192); }
    get CHAR_DELETE_FAILED() {return this.prop(193); }
    get CHAR_DELETE_FAILED_ARENA_CAPTAIN() {return this.prop(194); }
    get CHAR_DELETE_FAILED_GUILD_LEADER() {return this.prop(195); }
    get CHAR_DELETE_FAILED_LOCKED_FOR_TRANSFER() {return this.prop(196); }
    get CHAR_DELETE_IN_PROGRESS() {return this.prop(197); }
    get CHAR_DELETE_SUCCESS() {return this.prop(198); }
    get CHAR_FACTION_CHANGE_ARENA_LEADER() {return this.prop(199); }
    get CHAR_FACTION_CHANGE_CHOOSE_RACE() {return this.prop(200); }
    get CHAR_FACTION_CHANGE_DELETE_MAIL() {return this.prop(201); }
    get CHAR_FACTION_CHANGE_FAILED() {return this.prop(202); }
    get CHAR_FACTION_CHANGE_FORCE_LOGIN() {return this.prop(203); }
    get CHAR_FACTION_CHANGE_GOLD_LIMIT() {return this.prop(204); }
    get CHAR_FACTION_CHANGE_RACECLASS_RESTRICTED() {return this.prop(205); }
    get CHAR_FACTION_CHANGE_RACE_ONLY() {return this.prop(206); }
    get CHAR_FACTION_CHANGE_STILL_IN_ARENA() {return this.prop(207); }
    get CHAR_FACTION_CHANGE_STILL_IN_GUILD() {return this.prop(208); }
    get CHAR_FACTION_CHANGE_SWAP_FACTION() {return this.prop(209); }
    get CHAR_LIST_FAILED() {return this.prop(210); }
    get CHAR_LIST_RETRIEVED() {return this.prop(211); }
    get CHAR_LIST_RETRIEVING() {return this.prop(212); }
    get CHAR_LOGIN_DISABLED() {return this.prop(213); }
    get CHAR_LOGIN_DUPLICATE_CHARACTER() {return this.prop(214); }
    get CHAR_LOGIN_FAILED() {return this.prop(215); }
    get CHAR_LOGIN_IN_PROGRESS() {return this.prop(216); }
    get CHAR_LOGIN_LOCKED_BY_BILLING() {return this.prop(217); }
    get CHAR_LOGIN_LOCKED_BY_MOBILE_AH() {return this.prop(218); }
    get CHAR_LOGIN_LOCKED_FOR_TRANSFER() {return this.prop(219); }
    get CHAR_LOGIN_NO_CHARACTER() {return this.prop(220); }
    get CHAR_LOGIN_NO_INSTANCES() {return this.prop(221); }
    get CHAR_LOGIN_NO_WORLD() {return this.prop(222); }
    get CHAR_LOGIN_SUCCESS() {return this.prop(223); }
    get CHAR_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME() {return this.prop(224); }
    get CHAR_NAME_FAILURE() {return this.prop(225); }
    get CHAR_NAME_INVALID_APOSTROPHE() {return this.prop(226); }
    get CHAR_NAME_INVALID_CHARACTER() {return this.prop(227); }
    get CHAR_NAME_INVALID_SPACE() {return this.prop(228); }
    get CHAR_NAME_MIXED_LANGUAGES() {return this.prop(229); }
    get CHAR_NAME_MULTIPLE_APOSTROPHES() {return this.prop(230); }
    get CHAR_NAME_NO_NAME() {return this.prop(231); }
    get CHAR_NAME_PROFANE() {return this.prop(232); }
    get CHAR_NAME_RESERVED() {return this.prop(233); }
    get CHAR_NAME_RUSSIAN_CONSECUTIVE_SILENT_CHARACTERS() {return this.prop(234); }
    get CHAR_NAME_RUSSIAN_SILENT_CHARACTER_AT_BEGINNING_OR_END() {return this.prop(235); }
    get CHAR_NAME_THREE_CONSECUTIVE() {return this.prop(236); }
    get CHAR_NAME_TOO_LONG() {return this.prop(237); }
    get CHAR_NAME_TOO_SHORT() {return this.prop(238); }
    get CHAR_RENAME_DESCRIPTION() {return this.prop(239); }
    get CHAR_RENAME_FAILED() {return this.prop(240); }
    get CHAR_RENAME_INSTRUCTIONS() {return this.prop(241); }
    get CHAR_RENAME_IN_PROGRESS() {return this.prop(242); }
    get CHOOSE_CLASS() {return this.prop(243); }
    get CHOOSE_GENDER() {return this.prop(244); }
    get CHOOSE_LOCATION() {return this.prop(245); }
    get CHOOSE_LOCATION_DESCRIPTION() {return this.prop(246); }
    get CHOOSE_RACE() {return this.prop(247); }
    get CHOOSE_REALM_STYLE() {return this.prop(248); }
    get CINEMATICS() {return this.prop(249); }
    get CINEMATIC_SUBTITLES() {return this.prop(250); }
    get CLASS() {return this.prop(251); }
    get CLASS_DEATHKNIGHT() {return this.prop(252); }
    get CLASS_DEATHKNIGHT_FEMALE() {return this.prop(253); }
    get CLASS_DRUID() {return this.prop(254); }
    get CLASS_DRUID_FEMALE() {return this.prop(255); }
    get CLASS_HUNTER() {return this.prop(256); }
    get CLASS_HUNTER_FEMALE() {return this.prop(257); }
    get CLASS_INFO_DEATHKNIGHT0() {return this.prop(258); }
    get CLASS_INFO_DEATHKNIGHT1() {return this.prop(259); }
    get CLASS_INFO_DEATHKNIGHT2() {return this.prop(260); }
    get CLASS_INFO_DEATHKNIGHT3() {return this.prop(261); }
    get CLASS_INFO_DEATHKNIGHT4() {return this.prop(262); }
    get CLASS_INFO_DEATHKNIGHT5() {return this.prop(263); }
    get CLASS_INFO_DRUID0() {return this.prop(264); }
    get CLASS_INFO_DRUID1() {return this.prop(265); }
    get CLASS_INFO_DRUID2() {return this.prop(266); }
    get CLASS_INFO_DRUID3() {return this.prop(267); }
    get CLASS_INFO_DRUID4() {return this.prop(268); }
    get CLASS_INFO_HUNTER0() {return this.prop(269); }
    get CLASS_INFO_HUNTER1() {return this.prop(270); }
    get CLASS_INFO_HUNTER2() {return this.prop(271); }
    get CLASS_INFO_HUNTER3() {return this.prop(272); }
    get CLASS_INFO_HUNTER4() {return this.prop(273); }
    get CLASS_INFO_MAGE0() {return this.prop(274); }
    get CLASS_INFO_MAGE1() {return this.prop(275); }
    get CLASS_INFO_MAGE2() {return this.prop(276); }
    get CLASS_INFO_MAGE3() {return this.prop(277); }
    get CLASS_INFO_MAGE4() {return this.prop(278); }
    get CLASS_INFO_MAGE5() {return this.prop(279); }
    get CLASS_INFO_PALADIN0() {return this.prop(280); }
    get CLASS_INFO_PALADIN1() {return this.prop(281); }
    get CLASS_INFO_PALADIN2() {return this.prop(282); }
    get CLASS_INFO_PALADIN3() {return this.prop(283); }
    get CLASS_INFO_PALADIN4() {return this.prop(284); }
    get CLASS_INFO_PALADIN5() {return this.prop(285); }
    get CLASS_INFO_PRIEST0() {return this.prop(286); }
    get CLASS_INFO_PRIEST1() {return this.prop(287); }
    get CLASS_INFO_PRIEST2() {return this.prop(288); }
    get CLASS_INFO_PRIEST3() {return this.prop(289); }
    get CLASS_INFO_PRIEST4() {return this.prop(290); }
    get CLASS_INFO_ROGUE0() {return this.prop(291); }
    get CLASS_INFO_ROGUE1() {return this.prop(292); }
    get CLASS_INFO_ROGUE2() {return this.prop(293); }
    get CLASS_INFO_ROGUE3() {return this.prop(294); }
    get CLASS_INFO_ROGUE4() {return this.prop(295); }
    get CLASS_INFO_ROGUE5() {return this.prop(296); }
    get CLASS_INFO_SHAMAN0() {return this.prop(297); }
    get CLASS_INFO_SHAMAN1() {return this.prop(298); }
    get CLASS_INFO_SHAMAN2() {return this.prop(299); }
    get CLASS_INFO_SHAMAN3() {return this.prop(300); }
    get CLASS_INFO_SHAMAN4() {return this.prop(301); }
    get CLASS_INFO_SHAMAN5() {return this.prop(302); }
    get CLASS_INFO_WARLOCK0() {return this.prop(303); }
    get CLASS_INFO_WARLOCK1() {return this.prop(304); }
    get CLASS_INFO_WARLOCK2() {return this.prop(305); }
    get CLASS_INFO_WARLOCK3() {return this.prop(306); }
    get CLASS_INFO_WARLOCK4() {return this.prop(307); }
    get CLASS_INFO_WARLOCK5() {return this.prop(308); }
    get CLASS_INFO_WARRIOR0() {return this.prop(309); }
    get CLASS_INFO_WARRIOR1() {return this.prop(310); }
    get CLASS_INFO_WARRIOR2() {return this.prop(311); }
    get CLASS_INFO_WARRIOR3() {return this.prop(312); }
    get CLASS_INFO_WARRIOR4() {return this.prop(313); }
    get CLASS_MAGE() {return this.prop(314); }
    get CLASS_MAGE_FEMALE() {return this.prop(315); }
    get CLASS_PALADIN() {return this.prop(316); }
    get CLASS_PALADIN_FEMALE() {return this.prop(317); }
    get CLASS_PRIEST() {return this.prop(318); }
    get CLASS_PRIEST_FEMALE() {return this.prop(319); }
    get CLASS_ROGUE() {return this.prop(320); }
    get CLASS_ROGUE_FEMALE() {return this.prop(321); }
    get CLASS_SHAMAN() {return this.prop(322); }
    get CLASS_SHAMAN_FEMALE() {return this.prop(323); }
    get CLASS_WARLOCK() {return this.prop(324); }
    get CLASS_WARLOCK_FEMALE() {return this.prop(325); }
    get CLASS_WARRIOR() {return this.prop(326); }
    get CLASS_WARRIOR_FEMALE() {return this.prop(327); }
    get CLEAR() {return this.prop(328); }
    get CLEARMATRIX() {return this.prop(329); }
    get CLICK_TO_LAUNCH_ADDON_URL() {return this.prop(330); }
    get CLIENT_ACCOUNT_MISMATCH_BC() {return this.prop(331); }
    get CLIENT_ACCOUNT_MISMATCH_LK() {return this.prop(332); }
    get CLIENT_CONVERTED_TEXT() {return this.prop(333); }
    get CLIENT_CONVERTED_TITLE() {return this.prop(334); }
    get CLIENT_RESTART_ALERT() {return this.prop(335); }
    get CLIENT_TRIAL() {return this.prop(336); }
    get CLOSE() {return this.prop(337); }
    get COMMUNITY_SITE() {return this.prop(338); }
    get COMMUNITY_URL() {return this.prop(339); }
    get CONFIGURE_MODS_FOR() {return this.prop(340); }
    get CONFIRM_CHAR_DELETE() {return this.prop(341); }
    get CONFIRM_CHAR_DELETE_INSTRUCTIONS() {return this.prop(342); }
    get CONFIRM_COMPLETE_EXPENSIVE_QUEST() {return this.prop(343); }
    get CONFIRM_DISABLE_ADDONS() {return this.prop(344); }
    get CONFIRM_LAUNCH_ADDON_URL() {return this.prop(345); }
    get CONFIRM_LOAD_ADDONS() {return this.prop(346); }
    get CONFIRM_PAID_SERVICE() {return this.prop(347); }
    get CONFIRM_PFC() {return this.prop(348); }
    get CONFIRM_RESET_SETTINGS() {return this.prop(349); }
    get CONFIRM_TEMP() {return this.prop(350); }
    get CONNECTION_HELP_FRAME_TITLE() {return this.prop(351); }
    get CONTEST_FRAME_TITLE() {return this.prop(352); }
    get CONTEST_NOTICE() {return this.prop(353); }
    get CREATE_ACCOUNT() {return this.prop(354); }
    get CREATE_CHARACTER() {return this.prop(355); }
    get CREATE_NEW_CHARACTER() {return this.prop(356); }
    get CREDITS() {return this.prop(357); }
    get CREDITS_WOW_BC() {return this.prop(358); }
    get CREDITS_WOW_CLASSIC() {return this.prop(359); }
    get CREDITS_WOW_LK() {return this.prop(360); }
    get CRIT() {return this.prop(361); }
    get CSTATUS_AUTHENTICATING() {return this.prop(362); }
    get CSTATUS_CONNECTING() {return this.prop(363); }
    get CSTATUS_NEGOTIATING_SECURITY() {return this.prop(364); }
    get CSTATUS_NEGOTIATION_COMPLETE() {return this.prop(365); }
    get CSTATUS_NEGOTIATION_FAILED() {return this.prop(366); }
    get CURRENT_SETTINGS() {return this.prop(367); }
    get CUSTOM() {return this.prop(368); }
    get CUSTOMIZE_CHARACTER() {return this.prop(369); }
    get DAYS_ABBR() {return this.prop(370); }
    get DEATHKNIGHT_DISABLED() {return this.prop(371); }
    get DEATH_EFFECT() {return this.prop(372); }
    get DEBUG_BUILD() {return this.prop(373); }
    get DECLENSION_SET() {return this.prop(374); }
    get DECLINE() {return this.prop(375); }
    get DEFAULTS() {return this.prop(376); }
    get DEFENSE() {return this.prop(377); }
    get DELETE_CHARACTER() {return this.prop(378); }
    get DELETE_CONFIRM_STRING() {return this.prop(379); }
    get DEPTH_CONVERGENCE() {return this.prop(380); }
    get DESKTOP_GAMMA() {return this.prop(381); }
    get DISABLE_ADDONS() {return this.prop(382); }
    get DISABLE_ALL_ADDONS() {return this.prop(383); }
    get DISCONNECTED() {return this.prop(384); }
    get DISPLAY() {return this.prop(385); }
    get DMG() {return this.prop(386); }
    get DODGE() {return this.prop(387); }
    get DONE() {return this.prop(388); }
    get DOWNLOADING_UPDATE() {return this.prop(389); }
    get DOWNLOAD_SUCCESSFUL() {return this.prop(390); }
    get DOWNLOAD_SUCCESSFUL_TEXT() {return this.prop(391); }
    get DPS() {return this.prop(392); }
    get DRAENEI_DISABLED() {return this.prop(393); }
    get DRUID_DISABLED() {return this.prop(394); }
    get DURABILITY() {return this.prop(395); }
    get EFFECTS_LABEL() {return this.prop(396); }
    get EFFECTS_SUBTEXT() {return this.prop(397); }
    get EMAIL_ADDRESS() {return this.prop(398); }
    get ENABLED_FOR_SOME() {return this.prop(399); }
    get ENABLE_ALL_ADDONS() {return this.prop(400); }
    get ENABLE_AMBIENCE() {return this.prop(401); }
    get ENABLE_BGSOUND() {return this.prop(402); }
    get ENABLE_DSP_EFFECTS() {return this.prop(403); }
    get ENABLE_EMOTE_SOUNDS() {return this.prop(404); }
    get ENABLE_ERROR_SPEECH() {return this.prop(405); }
    get ENABLE_HARDWARE() {return this.prop(406); }
    get ENABLE_MUSIC() {return this.prop(407); }
    get ENABLE_MUSIC_LOOPING() {return this.prop(408); }
    get ENABLE_PET_SOUNDS() {return this.prop(409); }
    get ENABLE_REVERB() {return this.prop(410); }
    get ENABLE_SOFTWARE_HRTF() {return this.prop(411); }
    get ENABLE_SOUND() {return this.prop(412); }
    get ENABLE_SOUNDFX() {return this.prop(413); }
    get ENABLE_SOUND_AT_CHARACTER() {return this.prop(414); }
    get ENABLE_STEREO_VIDEO() {return this.prop(415); }
    get ENTER_AUTHCODE_INFO() {return this.prop(416); }
    get ENTER_AUTHCODE_TITLE() {return this.prop(417); }
    get ENTER_EMAIL() {return this.prop(418); }
    get ENTER_PIN_NUMBER() {return this.prop(419); }
    get ENTER_WORLD() {return this.prop(420); }
    get ENVIRONMENT_DETAIL() {return this.prop(421); }
    get ENVIRONMENT_LABEL() {return this.prop(422); }
    get ENVIRONMENT_SUBTEXT() {return this.prop(423); }
    get EULA_FRAME_TITLE() {return this.prop(424); }
    get EULA_NOTICE() {return this.prop(425); }
    get EXIT_GAME() {return this.prop(426); }
    get EYE_SEPARATION() {return this.prop(427); }
    get FACIAL_HAIR_EARRINGS() {return this.prop(428); }
    get FACIAL_HAIR_FEATURES() {return this.prop(429); }
    get FACIAL_HAIR_HAIR() {return this.prop(430); }
    get FACIAL_HAIR_HORNS() {return this.prop(431); }
    get FACIAL_HAIR_MARKINGS() {return this.prop(432); }
    get FACIAL_HAIR_NORMAL() {return this.prop(433); }
    get FACIAL_HAIR_PIERCINGS() {return this.prop(434); }
    get FACIAL_HAIR_TUSKS() {return this.prop(435); }
    get FACTION() {return this.prop(436); }
    get FACTION_CHANGE_IN_PROGRESS() {return this.prop(437); }
    get FACTION_INFO_ALLIANCE() {return this.prop(438); }
    get FACTION_INFO_HORDE() {return this.prop(439); }
    get FAR() {return this.prop(440); }
    get FARCLIP() {return this.prop(441); }
    get FEMALE() {return this.prop(442); }
    get FIX_LAG() {return this.prop(443); }
    get FRIENDS() {return this.prop(444); }
    get FULL_SCREEN_GLOW() {return this.prop(445); }
    get GAMETYPE_NORMAL() {return this.prop(446); }
    get GAMETYPE_PVE() {return this.prop(447); }
    get GAMETYPE_PVE_TEXT() {return this.prop(448); }
    get GAMETYPE_PVP() {return this.prop(449); }
    get GAMETYPE_PVP_TEXT() {return this.prop(450); }
    get GAMETYPE_RP() {return this.prop(451); }
    get GAMETYPE_RPPVP() {return this.prop(452); }
    get GAMETYPE_RPPVP_TEXT() {return this.prop(453); }
    get GAMETYPE_RP_TEXT() {return this.prop(454); }
    get GAME_SERVER_LOGIN() {return this.prop(455); }
    get GAME_SOUND_OUTPUT() {return this.prop(456); }
    get GAME_UPDATES() {return this.prop(457); }
    get GAMMA() {return this.prop(458); }
    get GENERAL_LABEL() {return this.prop(459); }
    get GM_BUILD() {return this.prop(460); }
    get GROUND_DENSITY() {return this.prop(461); }
    get GROUND_RADIUS() {return this.prop(462); }
    get HAIR_HORNS_COLOR() {return this.prop(463); }
    get HAIR_HORNS_STYLE() {return this.prop(464); }
    get HAIR_NORMAL_COLOR() {return this.prop(465); }
    get HAIR_NORMAL_STYLE() {return this.prop(466); }
    get HARDWARE() {return this.prop(467); }
    get HARDWARE_CURSOR() {return this.prop(468); }
    get HARDWARE_SURVEY_AGREE() {return this.prop(469); }
    get HARDWARE_SURVEY_DISAGREE() {return this.prop(470); }
    get HARDWARE_SURVEY_TITLE() {return this.prop(471); }
    get HELP() {return this.prop(472); }
    get HERTZ() {return this.prop(473); }
    get HIGH() {return this.prop(474); }
    get HIT() {return this.prop(475); }
    get HORDE() {return this.prop(476); }
    get HOURS_ABBR() {return this.prop(477); }
    get HUNTER_DISABLED() {return this.prop(478); }
    get IDLE_LOGOUT_WARNING() {return this.prop(479); }
    get INT() {return this.prop(480); }
    get LATEST_AGREEMENTS_URL() {return this.prop(481); }
    get LATEST_EULA_URL() {return this.prop(482); }
    get LATEST_TERMINATION_WITHOUT_NOTICE_URL() {return this.prop(483); }
    get LATEST_TOS_URL() {return this.prop(484); }
    get LAUNCH_FAILED() {return this.prop(485); }
    get LAUNCH_MAC_SYSTEM_REQUIRED() {return this.prop(486); }
    get LAUNCH_QUICKTIME_REQUIRED() {return this.prop(487); }
    get LAUNCH_USE_SOFTWARE_UPDATE() {return this.prop(488); }
    get LAUNCH_VIDEO_CARD_UNSUPPORTED() {return this.prop(489); }
    get LEVEL() {return this.prop(490); }
    get LOAD_ADDONS() {return this.prop(491); }
    get LOAD_FULL() {return this.prop(492); }
    get LOAD_HIGH() {return this.prop(493); }
    get LOAD_LOW() {return this.prop(494); }
    get LOAD_MEDIUM() {return this.prop(495); }
    get LOAD_NEW() {return this.prop(496); }
    get LOAD_RECOMMENDED() {return this.prop(497); }
    get LOGIN() {return this.prop(498); }
    get LOGIN_ACCOUNT_CONVERTED() {return this.prop(499); }
    get LOGIN_ACCOUNT_LOCKED() {return this.prop(500); }
    get LOGIN_ALREADYONLINE() {return this.prop(501); }
    get LOGIN_ANTI_INDULGENCE() {return this.prop(502); }
    get LOGIN_AUTH_OUTAGE() {return this.prop(503); }
    get LOGIN_BADVERSION() {return this.prop(504); }
    get LOGIN_BAD_SERVER_PROOF() {return this.prop(505); }
    get LOGIN_BAD_SERVER_RECODE_PROOF() {return this.prop(506); }
    get LOGIN_BANNED() {return this.prop(507); }
    get LOGIN_CHARGEBACK() {return this.prop(508); }
    get LOGIN_CONVERSION_REQUIRED() {return this.prop(509); }
    get LOGIN_DBBUSY() {return this.prop(510); }
    get LOGIN_ENTER_NAME() {return this.prop(511); }
    get LOGIN_ENTER_PASSWORD() {return this.prop(512); }
    get LOGIN_ERROR() {return this.prop(513); }
    get LOGIN_EXPIRED() {return this.prop(514); }
    get LOGIN_FAILED() {return this.prop(515); }
    get LOGIN_GAME_ACCOUNT_LOCKED() {return this.prop(516); }
    get LOGIN_IGR_WITHOUT_BNET() {return this.prop(517); }
    get LOGIN_INCORRECT_PASSWORD() {return this.prop(518); }
    get LOGIN_INVALID_CHALLENGE_MESSAGE() {return this.prop(519); }
    get LOGIN_INVALID_PROOF_MESSAGE() {return this.prop(520); }
    get LOGIN_INVALID_RECODE_MESSAGE() {return this.prop(521); }
    get LOGIN_LOCALE_MISMATCH() {return this.prop(522); }
    get LOGIN_LOCKED_ENFORCED() {return this.prop(523); }
    get LOGIN_MALFORMED_ACCOUNT_NAME() {return this.prop(524); }
    get LOGIN_NOTIME() {return this.prop(525); }
    get LOGIN_NO_BATTLENET_APPLICATION() {return this.prop(526); }
    get LOGIN_NO_BATTLENET_MANAGER() {return this.prop(527); }
    get LOGIN_NO_GAME_ACCOUNT() {return this.prop(528); }
    get LOGIN_NO_GAME_ACCOUNTS_IN_REGION_NONE() {return this.prop(529); }
    get LOGIN_PARENTALCONTROL() {return this.prop(530); }
    get LOGIN_SERVER_DOWN() {return this.prop(531); }
    get LOGIN_SRP_ERROR() {return this.prop(532); }
    get LOGIN_STATE_AUTHENTICATED() {return this.prop(533); }
    get LOGIN_STATE_AUTHENTICATING() {return this.prop(534); }
    get LOGIN_STATE_CHECKINGVERSIONS() {return this.prop(535); }
    get LOGIN_STATE_CONNECTING() {return this.prop(536); }
    get LOGIN_STATE_DOWNLOADFILE() {return this.prop(537); }
    get LOGIN_STATE_HANDSHAKING() {return this.prop(538); }
    get LOGIN_STATE_INITIALIZED() {return this.prop(539); }
    get LOGIN_STATE_SURVEY() {return this.prop(540); }
    get LOGIN_SUSPENDED() {return this.prop(541); }
    get LOGIN_TOO_FAST() {return this.prop(542); }
    get LOGIN_TRIAL_EXPIRED() {return this.prop(543); }
    get LOGIN_UNKNOWN_ACCOUNT() {return this.prop(544); }
    get LOGIN_UNKNOWN_ACCOUNT_CALL() {return this.prop(545); }
    get LOGIN_UNKNOWN_ACCOUNT_PIN() {return this.prop(546); }
    get LOGIN_UNLOCKABLE_LOCK() {return this.prop(547); }
    get LOGIN_USE_GRUNT() {return this.prop(548); }
    get LOW() {return this.prop(549); }
    get MAGE_DISABLED() {return this.prop(550); }
    get MALE() {return this.prop(551); }
    get MANAGE_ACCOUNT() {return this.prop(552); }
    get MASTER_VOLUME() {return this.prop(553); }
    get MELEE_CRIT() {return this.prop(554); }
    get MENU_ABOUT() {return this.prop(555); }
    get MENU_EDIT() {return this.prop(556); }
    get MENU_EDIT_COPY() {return this.prop(557); }
    get MENU_EDIT_CUT() {return this.prop(558); }
    get MENU_EDIT_PASTE() {return this.prop(559); }
    get MENU_EDIT_SELECT_ALL() {return this.prop(560); }
    get MENU_EDIT_UNDO() {return this.prop(561); }
    get MENU_SWITCH_TO_FULLSCREEN() {return this.prop(562); }
    get MINUTES() {return this.prop(563); }
    get MINUTES_ABBR() {return this.prop(564); }
    get MISCELLANEOUS() {return this.prop(565); }
    get MULTISAMPLE() {return this.prop(566); }
    get MULTISAMPLING_FORMAT_STRING() {return this.prop(567); }
    get MUSIC_VOLUME() {return this.prop(568); }
    get NAME() {return this.prop(569); }
    get NAME_AND_REST_STATE() {return this.prop(570); }
    get NEAR() {return this.prop(571); }
    get NEWS() {return this.prop(572); }
    get NEW_REALM() {return this.prop(573); }
    get NO() {return this.prop(574); }
    get NONE_CAPS() {return this.prop(575); }
    get NORMAL_BUILD() {return this.prop(576); }
    get OKAY() {return this.prop(577); }
    get OPTIONS() {return this.prop(578); }
    get OPTIONS_BRIGHTNESS() {return this.prop(579); }
    get OPTIONS_SHADERS() {return this.prop(580); }
    get OPTION_RESTART_REQUIREMENT() {return this.prop(581); }
    get OPTION_STEREO_CONVERGENCE() {return this.prop(582); }
    get OPTION_STEREO_SEPARATION() {return this.prop(583); }
    get OPTION_TOOLTIP_AMBIENCE_VOLUME() {return this.prop(584); }
    get OPTION_TOOLTIP_AMBIENT_VOLUME() {return this.prop(585); }
    get OPTION_TOOLTIP_ANISOTROPIC() {return this.prop(586); }
    get OPTION_TOOLTIP_CINEMATIC_SUBTITLES() {return this.prop(587); }
    get OPTION_TOOLTIP_DEATH_EFFECT() {return this.prop(588); }
    get OPTION_TOOLTIP_DESKTOP_GAMMA() {return this.prop(589); }
    get OPTION_TOOLTIP_ENABLE_AMBIENCE() {return this.prop(590); }
    get OPTION_TOOLTIP_ENABLE_BGSOUND() {return this.prop(591); }
    get OPTION_TOOLTIP_ENABLE_DSP_EFFECTS() {return this.prop(592); }
    get OPTION_TOOLTIP_ENABLE_EMOTE_SOUNDS() {return this.prop(593); }
    get OPTION_TOOLTIP_ENABLE_ERROR_SPEECH() {return this.prop(594); }
    get OPTION_TOOLTIP_ENABLE_HARDWARE() {return this.prop(595); }
    get OPTION_TOOLTIP_ENABLE_MUSIC() {return this.prop(596); }
    get OPTION_TOOLTIP_ENABLE_MUSIC_LOOPING() {return this.prop(597); }
    get OPTION_TOOLTIP_ENABLE_PET_SOUNDS() {return this.prop(598); }
    get OPTION_TOOLTIP_ENABLE_REVERB() {return this.prop(599); }
    get OPTION_TOOLTIP_ENABLE_SOFTWARE_HRTF() {return this.prop(600); }
    get OPTION_TOOLTIP_ENABLE_SOUND() {return this.prop(601); }
    get OPTION_TOOLTIP_ENABLE_SOUNDFX() {return this.prop(602); }
    get OPTION_TOOLTIP_ENABLE_SOUND_AT_CHARACTER() {return this.prop(603); }
    get OPTION_TOOLTIP_ENABLE_STEREO_VIDEO() {return this.prop(604); }
    get OPTION_TOOLTIP_ENVIRONMENT_DETAIL() {return this.prop(605); }
    get OPTION_TOOLTIP_FARCLIP() {return this.prop(606); }
    get OPTION_TOOLTIP_FIX_LAG() {return this.prop(607); }
    get OPTION_TOOLTIP_FULL_SCREEN_GLOW() {return this.prop(608); }
    get OPTION_TOOLTIP_GAMMA() {return this.prop(609); }
    get OPTION_TOOLTIP_GROUND_DENSITY() {return this.prop(610); }
    get OPTION_TOOLTIP_GROUND_RADIUS() {return this.prop(611); }
    get OPTION_TOOLTIP_HARDWARE_CURSOR() {return this.prop(612); }
    get OPTION_TOOLTIP_MASTER_VOLUME() {return this.prop(613); }
    get OPTION_TOOLTIP_MULTISAMPLING() {return this.prop(614); }
    get OPTION_TOOLTIP_MUSIC_VOLUME() {return this.prop(615); }
    get OPTION_TOOLTIP_PARTICLE_DENSITY() {return this.prop(616); }
    get OPTION_TOOLTIP_PLAYER_DETAIL() {return this.prop(617); }
    get OPTION_TOOLTIP_PROJECTED_TEXTURES() {return this.prop(618); }
    get OPTION_TOOLTIP_SHADOW_QUALITY() {return this.prop(619); }
    get OPTION_TOOLTIP_SOUND_CHANNELS() {return this.prop(620); }
    get OPTION_TOOLTIP_SOUND_OUTPUT() {return this.prop(621); }
    get OPTION_TOOLTIP_SOUND_QUALITY() {return this.prop(622); }
    get OPTION_TOOLTIP_SOUND_VOLUME() {return this.prop(623); }
    get OPTION_TOOLTIP_SPELL_DETAIL() {return this.prop(624); }
    get OPTION_TOOLTIP_STEREO_HARDWARE_CURSOR() {return this.prop(625); }
    get OPTION_TOOLTIP_TERRAIN_HIGHLIGHTS() {return this.prop(626); }
    get OPTION_TOOLTIP_TERRAIN_TEXTURE() {return this.prop(627); }
    get OPTION_TOOLTIP_TEXTURE_DETAIL() {return this.prop(628); }
    get OPTION_TOOLTIP_TRIPLE_BUFFER() {return this.prop(629); }
    get OPTION_TOOLTIP_USE_REFRESH() {return this.prop(630); }
    get OPTION_TOOLTIP_USE_RESOLUTION() {return this.prop(631); }
    get OPTION_TOOLTIP_VERTICAL_SYNC() {return this.prop(632); }
    get OPTION_TOOLTIP_WEATHER_DETAIL() {return this.prop(633); }
    get OPTION_TOOLTIP_WINDOWED_MAXIMIZED() {return this.prop(634); }
    get OPTION_TOOLTIP_WINDOWED_MODE() {return this.prop(635); }
    get OPTION_TOOLTIP_WINDOW_LOCK() {return this.prop(636); }
    get OPTION_TOOLTIP_WORLD_LOD() {return this.prop(637); }
    get OPTION_UI_DEPTH() {return this.prop(638); }
    get OUTBID_ON_SHORT() {return this.prop(639); }
    get PAID_CHARACTER_CUSTOMIZE_TOOLTIP() {return this.prop(640); }
    get PAID_FACTION_CHANGE_TOOLTIP() {return this.prop(641); }
    get PAID_RACE_CHANGE_TOOLTIP() {return this.prop(642); }
    get PALADIN_DISABLED() {return this.prop(643); }
    get PARRY() {return this.prop(644); }
    get PARTICLE_DENSITY() {return this.prop(645); }
    get PASSWORD() {return this.prop(646); }
    get PATCH_FAILED_DISK_FULL() {return this.prop(647); }
    get PATCH_FAILED_MESSAGE() {return this.prop(648); }
    get PENETRATION() {return this.prop(649); }
    get PIXEL_SHADERS() {return this.prop(650); }
    get PLAYBACK() {return this.prop(651); }
    get PLAYER_DETAIL() {return this.prop(652); }
    get POWER() {return this.prop(653); }
    get PRIEST_DISABLED() {return this.prop(654); }
    get PROJECTED_TEXTURES() {return this.prop(655); }
    get PTR_AE_BUILD() {return this.prop(656); }
    get PTR_RELEASE_BUILD() {return this.prop(657); }
    get PVP_PARENTHESES() {return this.prop(658); }
    get QUEUE_FCM() {return this.prop(659); }
    get QUEUE_FCM_BUTTON() {return this.prop(660); }
    get QUEUE_FCM_URL() {return this.prop(661); }
    get QUEUE_NAME_TIME_LEFT() {return this.prop(662); }
    get QUEUE_NAME_TIME_LEFT_SECONDS() {return this.prop(663); }
    get QUEUE_NAME_TIME_LEFT_UNKNOWN() {return this.prop(664); }
    get QUEUE_TIME_LEFT() {return this.prop(665); }
    get QUEUE_TIME_LEFT_SECONDS() {return this.prop(666); }
    get QUEUE_TIME_LEFT_UNKNOWN() {return this.prop(667); }
    get QUIT() {return this.prop(668); }
    get RACE() {return this.prop(669); }
    get RACE_CHANGE_IN_PROGRESS() {return this.prop(670); }
    get RACE_INFO_BLOODELF() {return this.prop(671); }
    get RACE_INFO_BLOODELF_FEMALE() {return this.prop(672); }
    get RACE_INFO_DRAENEI() {return this.prop(673); }
    get RACE_INFO_DRAENEI_FEMALE() {return this.prop(674); }
    get RACE_INFO_DWARF() {return this.prop(675); }
    get RACE_INFO_DWARF_FEMALE() {return this.prop(676); }
    get RACE_INFO_GNOME() {return this.prop(677); }
    get RACE_INFO_GNOME_FEMALE() {return this.prop(678); }
    get RACE_INFO_HUMAN() {return this.prop(679); }
    get RACE_INFO_HUMAN_FEMALE() {return this.prop(680); }
    get RACE_INFO_NIGHTELF() {return this.prop(681); }
    get RACE_INFO_NIGHTELF_FEMALE() {return this.prop(682); }
    get RACE_INFO_ORC() {return this.prop(683); }
    get RACE_INFO_ORC_FEMALE() {return this.prop(684); }
    get RACE_INFO_SCOURGE() {return this.prop(685); }
    get RACE_INFO_SCOURGE_FEMALE() {return this.prop(686); }
    get RACE_INFO_TAUREN() {return this.prop(687); }
    get RACE_INFO_TAUREN_FEMALE() {return this.prop(688); }
    get RACE_INFO_TROLL() {return this.prop(689); }
    get RACE_INFO_TROLL_FEMALE() {return this.prop(690); }
    get RACIAL_ABILITIES() {return this.prop(691); }
    get RANDOMIZE() {return this.prop(692); }
    get RATINGS_TEXT() {return this.prop(693); }
    get REALMLIST_NUMCHARACTERS_TOOLTIP() {return this.prop(694); }
    get REALMLIST_POPULATION_TOOLTIP() {return this.prop(695); }
    get REALMLIST_REALMNAME_TOOLTIP() {return this.prop(696); }
    get REALMLIST_TYPE_TOOLTIP() {return this.prop(697); }
    get REALM_CHARACTERS() {return this.prop(698); }
    get REALM_DESCRIPTION() {return this.prop(699); }
    get REALM_DESCRIPTION_TEXT() {return this.prop(700); }
    get REALM_DOWN() {return this.prop(701); }
    get REALM_HELP_FRAME_TEXT() {return this.prop(702); }
    get REALM_HELP_FRAME_TITLE() {return this.prop(703); }
    get REALM_HELP_FRAME_URL() {return this.prop(704); }
    get REALM_INFO_TEMPLATE() {return this.prop(705); }
    get REALM_IS_FULL_WARNING() {return this.prop(706); }
    get REALM_LIST_FAILED() {return this.prop(707); }
    get REALM_LIST_INVALID() {return this.prop(708); }
    get REALM_LIST_IN_PROGRESS() {return this.prop(709); }
    get REALM_LIST_REALM_NOT_FOUND() {return this.prop(710); }
    get REALM_LIST_SUCCESS() {return this.prop(711); }
    get REALM_LOAD() {return this.prop(712); }
    get REALM_LOCKED() {return this.prop(713); }
    get REALM_NAME() {return this.prop(714); }
    get REALM_TYPE() {return this.prop(715); }
    get REALM_TYPE_LOCALE_WARNING() {return this.prop(716); }
    get REALM_TYPE_TOURNAMENT_WARNING() {return this.prop(717); }
    get REFRESH_RATE() {return this.prop(718); }
    get REGEN() {return this.prop(719); }
    get RELEASE_BUILD() {return this.prop(720); }
    get RESET_SERVER_SETTINGS() {return this.prop(721); }
    get RESET_SETTINGS() {return this.prop(722); }
    get RESET_WARNING() {return this.prop(723); }
    get RESILIENCE() {return this.prop(724); }
    get RESOLUTION() {return this.prop(725); }
    get RESOLUTION_LABEL() {return this.prop(726); }
    get RESOLUTION_SUBTEXT() {return this.prop(727); }
    get RESPONSE_CANCELLED() {return this.prop(728); }
    get RESPONSE_CONNECTED() {return this.prop(729); }
    get RESPONSE_DISCONNECTED() {return this.prop(730); }
    get RESPONSE_FAILED_TO_CONNECT() {return this.prop(731); }
    get RESPONSE_FAILURE() {return this.prop(732); }
    get RESPONSE_SUCCESS() {return this.prop(733); }
    get RESPONSE_VERSION_MISMATCH() {return this.prop(734); }
    get RESTART() {return this.prop(735); }
    get RETURN_TO_LOGIN() {return this.prop(736); }
    get ROGUE_DISABLED() {return this.prop(737); }
    get ROLE_DAMAGER() {return this.prop(738); }
    get ROLE_HEALER() {return this.prop(739); }
    get ROLE_TANK() {return this.prop(740); }
    get RPPVP_PARENTHESES() {return this.prop(741); }
    get RP_PARENTHESES() {return this.prop(742); }
    get RUSSIAN_DECLENSION() {return this.prop(743); }
    get RUSSIAN_DECLENSION_1() {return this.prop(744); }
    get RUSSIAN_DECLENSION_2() {return this.prop(745); }
    get RUSSIAN_DECLENSION_3() {return this.prop(746); }
    get RUSSIAN_DECLENSION_4() {return this.prop(747); }
    get RUSSIAN_DECLENSION_5() {return this.prop(748); }
    get RUSSIAN_DECLENSION_EXAMPLE_1() {return this.prop(749); }
    get RUSSIAN_DECLENSION_EXAMPLE_2() {return this.prop(750); }
    get RUSSIAN_DECLENSION_EXAMPLE_3() {return this.prop(751); }
    get RUSSIAN_DECLENSION_EXAMPLE_4() {return this.prop(752); }
    get RUSSIAN_DECLENSION_EXAMPLE_5() {return this.prop(753); }
    get SAVE_ACCOUNT_NAME() {return this.prop(754); }
    get SCANDLL_BUTTON_CONTINUEANYWAY() {return this.prop(755); }
    get SCANDLL_BUTTON_MOREINFO() {return this.prop(756); }
    get SCANDLL_MESSAGE_DOWNLOADING() {return this.prop(757); }
    get SCANDLL_MESSAGE_ERROR() {return this.prop(758); }
    get SCANDLL_MESSAGE_HACK() {return this.prop(759); }
    get SCANDLL_MESSAGE_HACKFOUND_CONFIRM() {return this.prop(760); }
    get SCANDLL_MESSAGE_HACKNOCONTINUE() {return this.prop(761); }
    get SCANDLL_MESSAGE_SCANNING() {return this.prop(762); }
    get SCANDLL_MESSAGE_TROJAN() {return this.prop(763); }
    get SCANDLL_MESSAGE_TROJANFOUND_CONFIRM() {return this.prop(764); }
    get SCANDLL_URL_HACK() {return this.prop(765); }
    get SCANDLL_URL_LAUNCHER_TXT() {return this.prop(766); }
    get SCANDLL_URL_TROJAN() {return this.prop(767); }
    get SCANDLL_URL_WIN32_SCAN_DLL() {return this.prop(768); }
    get SCANNING_NOTICE() {return this.prop(769); }
    get SCAN_FRAME_TITLE() {return this.prop(770); }
    get SECONDS() {return this.prop(771); }
    get SECONDS_ABBR() {return this.prop(772); }
    get SECURITYMATRIX_DIRECTIONS() {return this.prop(773); }
    get SECURITYMATRIX_ENTER_CELL() {return this.prop(774); }
    get SELECT_ACCOUNT() {return this.prop(775); }
    get SELECT_CHARACTER() {return this.prop(776); }
    get SELECT_RACE() {return this.prop(777); }
    get SERVER_ALERT_BETA_URL() {return this.prop(778); }
    get SERVER_ALERT_BUTTON_TEXT() {return this.prop(779); }
    get SERVER_ALERT_PTR_URL() {return this.prop(780); }
    get SERVER_ALERT_TITLE() {return this.prop(781); }
    get SERVER_ALERT_URL() {return this.prop(782); }
    get SERVER_DOWN() {return this.prop(783); }
    get SERVER_SELECTION() {return this.prop(784); }
    get SERVER_SPLIT() {return this.prop(785); }
    get SERVER_SPLIT_BUTTON() {return this.prop(786); }
    get SERVER_SPLIT_CHOOSE_BY() {return this.prop(787); }
    get SERVER_SPLIT_CURRENT_CHOICE() {return this.prop(788); }
    get SERVER_SPLIT_DONT_CHANGE() {return this.prop(789); }
    get SERVER_SPLIT_NOT_NOW() {return this.prop(790); }
    get SERVER_SPLIT_PENDING() {return this.prop(791); }
    get SERVER_SPLIT_REALM_CHOICE() {return this.prop(792); }
    get SERVER_SPLIT_SERVER_ONE() {return this.prop(793); }
    get SERVER_SPLIT_SERVER_TWO() {return this.prop(794); }
    get SHADOW_QUALITY() {return this.prop(795); }
    get SHAMAN_DISABLED() {return this.prop(796); }
    get SHOW_LAUNCHER() {return this.prop(797); }
    get SKILLLINES() {return this.prop(798); }
    get SOUL_SHARD() {return this.prop(799); }
    get SOUNDOPTIONS_MENU() {return this.prop(800); }
    get SOUND_CHANNELS() {return this.prop(801); }
    get SOUND_LABEL() {return this.prop(802); }
    get SOUND_QUALITY() {return this.prop(803); }
    get SOUND_SUBTEXT() {return this.prop(804); }
    get SOUND_VOLUME() {return this.prop(805); }
    get SPD() {return this.prop(806); }
    get SPEED() {return this.prop(807); }
    get SPELL_DETAIL() {return this.prop(808); }
    get SPI() {return this.prop(809); }
    get STA() {return this.prop(810); }
    get STEREO_HARDWARE_CURSOR() {return this.prop(811); }
    get STEREO_VIDEO_LABEL() {return this.prop(812); }
    get STEREO_VIDEO_SUBTEXT() {return this.prop(813); }
    get STR() {return this.prop(814); }
    get STREAMING_BUILD() {return this.prop(815); }
    get SUGGESTED_REALM_TEXT() {return this.prop(816); }
    get SUGGEST_REALM() {return this.prop(817); }
    get SYSTEM_DEFAULT() {return this.prop(818); }
    get SYSTEM_INCOMPATIBLE_SSE() {return this.prop(819); }
    get TECH_SUPPORT() {return this.prop(820); }
    get TECH_SUPPORT_URL() {return this.prop(821); }
    get TEMP_ARMOR() {return this.prop(822); }
    get TEMP_SKILLS() {return this.prop(823); }
    get TEMP_WEAPON() {return this.prop(824); }
    get TERMINATION_WITHOUT_NOTICE_FRAME_TITLE() {return this.prop(825); }
    get TERMINATION_WITHOUT_NOTICE_NOTICE() {return this.prop(826); }
    get TERRAIN_HIGHLIGHTS() {return this.prop(827); }
    get TERRAIN_MIP() {return this.prop(828); }
    get TEXTURE_DETAIL() {return this.prop(829); }
    get TOS_ACCEPT() {return this.prop(830); }
    get TOS_FRAME_TITLE() {return this.prop(831); }
    get TOS_NOTICE() {return this.prop(832); }
    get TRIAL_LOADING_MESSAGE() {return this.prop(833); }
    get TRIPLE_BUFFER() {return this.prop(834); }
    get UI_DEPTH() {return this.prop(835); }
    get UNKNOWN_ZONE() {return this.prop(836); }
    get UPGRADE_ACCOUNT() {return this.prop(837); }
    get USE_ENGLISH_SPEECH_PACK() {return this.prop(838); }
    get VERSION() {return this.prop(839); }
    get VERSION_TEMPLATE() {return this.prop(840); }
    get VERTICAL_SYNC() {return this.prop(841); }
    get VIDEOOPTIONS_MENU() {return this.prop(842); }
    get VIDEO_OPTIONS_RESET() {return this.prop(843); }
    get VIDEO_QUALITY_LABEL1() {return this.prop(844); }
    get VIDEO_QUALITY_LABEL2() {return this.prop(845); }
    get VIDEO_QUALITY_LABEL3() {return this.prop(846); }
    get VIDEO_QUALITY_LABEL4() {return this.prop(847); }
    get VIDEO_QUALITY_LABEL5() {return this.prop(848); }
    get VIDEO_QUALITY_LABEL6() {return this.prop(849); }
    get VIDEO_QUALITY_S() {return this.prop(850); }
    get VIDEO_QUALITY_SUBTEXT1() {return this.prop(851); }
    get VIDEO_QUALITY_SUBTEXT2() {return this.prop(852); }
    get VIDEO_QUALITY_SUBTEXT3() {return this.prop(853); }
    get VIDEO_QUALITY_SUBTEXT4() {return this.prop(854); }
    get VIDEO_QUALITY_SUBTEXT5() {return this.prop(855); }
    get VIDEO_QUALITY_SUBTEXT6() {return this.prop(856); }
    get VIEW_ALL_REALMS() {return this.prop(857); }
    get VIRTUAL_KEYPAD_OKAY() {return this.prop(858); }
    get VOLUME() {return this.prop(859); }
    get WARLOCK_DISABLED() {return this.prop(860); }
    get WARRIOR_DISABLED() {return this.prop(861); }
    get WEAPONS() {return this.prop(862); }
    get WEAPON_SKILL() {return this.prop(863); }
    get WEATHER_DETAIL() {return this.prop(864); }
    get WEB_SITE() {return this.prop(865); }
    get WHISPER_FROM() {return this.prop(866); }
    get WIDESCREEN_TAG() {return this.prop(867); }
    get WINDOWED_MAXIMIZED() {return this.prop(868); }
    get WINDOWED_MODE() {return this.prop(869); }
    get WINDOW_LOCK() {return this.prop(870); }
    get WORLD_APPEARANCE() {return this.prop(871); }
    get WORLD_LOD() {return this.prop(872); }
    get WORLD_OF_WARCRAFT() {return this.prop(873); }
    get WOW_ACCOUNTS() {return this.prop(874); }
    get WRATH_OF_THE_LICH_KING() {return this.prop(875); }
    get YES() {return this.prop(876); }
}