
export enum CreatureFactionTemplate {
    NeutralNonAggressive = 7,
    Stormwind            = 11,
    NeutralHostile       = 21,
    NeutralPassive       = 35,
    Ironforge            = 57,
    Gnomeregan           = 64,
    Ratchet              = 69,
    Undercity            = 71,
    Darnassus            = 79,
    Orgrimmar            = 85,
    ThunderBluff         = 105,
    BloodsailBuccaneers  = 119,
    BootyBay             = 121,
    DarkspearTrolls      = 126,
    Gadgetzan            = 474,
    CenarionCircle       = 994,
    Silvermoon           = 1604,
    Exodar               = 1639,
    Shatar               = 1741,
    KirinTor             = 2007,
}